#!/usr/bin/env bash

# Replace localhost IP address from 127.0.0.1 to 127.0.0.2
sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts

# Add a new entry so facebook.com resolves to 8.8.8.8
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
