#!/usr/bin/env bash
# Configure Ubuntu server

sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts

if ! grep -q "facebook.com" /etc/hosts; then
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
