#!/usr/bin/env bash
# This script configures localhost and facebook.com IP addresses in /etc/hosts

grep -v "127.0.0.1 localhost" /etc/hosts > /tmp/hosts
echo "127.0.0.2 localhost" >> /tmp/hosts
echo "8.8.8.8 facebook.com" >> /tmp/hosts
cat /tmp/hosts > /etc/hosts
